export default [
  {
    name: "spices",
    ingredients: [
      "Chilli sauce",
      "Cinnamon",
      "Garlic powder",
      "Paprika",
      "Oregano",
      "Red pepper",
      "cumin",
      "cayenne",
      "thyme",
    ],
    image:
      "https://www.thespruceeats.com/thmb/RReGwC2-i-CsdWHcSEei1WWcGfw=/2500x1406/smart/filters:no_upscale()/spices-2500-56a20ee15f9b58b7d0c61d97.jpg",
  },
  {
    name: "meats",
    ingredients: [
      "chicken breast",
      "ground beef",
      "bacon",
      "sausage",
      "beef steak",
      "han",
      "hot dog",
      "pork chops",
      "chicken thights",
      "ground turkey",
      "pork",
      "turkey",
    ],
    image:
      "https://www.news-medical.net/image.axd?picture=2019%2F11%2Fshutterstock_1031664748.jpg",
  },
  {
    name: "vegetables",
    ingredients: [
      "onion",
      "garlic",
      "tomato",
      "lettuce",
      "potato",
      "carrot",
      "basil",
      "parsley",
      "broccoli",
      "corn",
      "spinach",
      "ginger",
    ],
    image:
      "https://img.webmd.com/dtmcms/live/webmd/consumer_assets/site_images/article_thumbnails/slideshows/powerhouse_vegetables_slideshow/650x350_powerhouse_vegetables_slideshow.jpg",
  },
  {
    name: "fruits",
    ingredients: [
      "cherry",
      "apple",
      "banana",
      "lime",
      "orange",
      "pineapple",
      "blueberry",
      "raisin",
      "coconut",
      "grape",
      "peach",
      "mango",
    ],
    image:
      "https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2020/02/325253_2200-1200x628.jpg",
  },
  {
    name: "fish",
    ingredients: [
      "canned tuna",
      "slamon",
      "tilapia",
      "fish fillets",
      "cod",
      "canned salmon",
      "smoked salmon",
      "trout",
      "haddock",
      "tuna steak",
      "mahi mahi",
      "swordfish",
    ],
    image:
      "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2012/5/4/1/FNM_060112-Duff-Goldman-Spanish-Style-Grilled-Fish-recipe_s4x3.jpg.rend.hgtvcom.826.620.suffix/1371606208411.jpeg",
  },
];
